<?xml version="1.0" encoding="utf-8"?><Database Name="np" Class="npDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=RENEGADE;Initial Catalog=np;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="AccountId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="DateCreatedUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateLastUpdatedUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Discriminator" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AddressId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email1" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="Account_AppointmentComment" Member="AppointmentComments" ThisKey="AccountId" OtherKey="AccountId" Type="AppointmentComment" />
      <Association Name="Account_Client" Member="Clients" ThisKey="AccountId" OtherKey="AccountId" Type="Client" />
      <Association Name="Account_Designer" Member="Designers" ThisKey="AccountId" OtherKey="AccountId" Type="Designer" />
      <Association Name="Account_Photo" Member="Photos" ThisKey="AccountId" OtherKey="AccountId" Type="Photo" />
      <Association Name="Account_UserClaim" Member="UserClaims" ThisKey="UserId" OtherKey="UserId" Type="UserClaim" />
      <Association Name="Account_UserLogin" Member="UserLogins" ThisKey="UserId" OtherKey="UserId" Type="UserLogin" />
      <Association Name="Account_UserRole" Member="UserRoles" ThisKey="UserId" OtherKey="UserId" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.WorkSchedule" Member="WorkSchedules">
    <Type Name="WorkSchedule">
      <Column Name="WorkScheduleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DesignerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="ClosedDatesLocation" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="Designer_WorkSchedule" Member="Designer" ThisKey="DesignerId" OtherKey="DesignerId" Type="Designer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Address" Member="Addresses">
    <Type Name="Address">
      <Column Name="AddressId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Address" Member="Address1" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Zip" Type="System.String" DbType="NChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AlernatePhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateCreatedUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateLastUpdatedUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ApplicationRoles" Member="ApplicationRoles">
    <Type Name="ApplicationRole">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ApplicationRole_UserRole" Member="UserRoles" ThisKey="Id" OtherKey="RoleId" Type="UserRole" />
    </Type>
  </Table>
  <Table Name="dbo.Appointment" Member="Appointments">
    <Type Name="Appointment">
      <Column Name="AppointmentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Designerd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ClientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AppointmentTimeUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateCreatedUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateConfirmed" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsCanceled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TimeOffset" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="Appointment_AppointmentComment" Member="AppointmentComments" ThisKey="AppointmentId" OtherKey="AppointmentId" Type="AppointmentComment" />
      <Association Name="Appointment_AppointmentNote" Member="AppointmentNotes" ThisKey="AppointmentId" OtherKey="AppointmentId" Type="AppointmentNote" />
      <Association Name="Client_Appointment" Member="Client" ThisKey="ClientId" OtherKey="ClientId" Type="Client" IsForeignKey="true" />
      <Association Name="Designer_Appointment" Member="Designer" ThisKey="Designerd" OtherKey="DesignerId" Type="Designer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AppointmentComment" Member="AppointmentComments">
    <Type Name="AppointmentComment">
      <Column Name="AppointmentCommentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AppointmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Account_AppointmentComment" Member="Account" ThisKey="AccountId" OtherKey="AccountId" Type="Account" IsForeignKey="true" />
      <Association Name="Appointment_AppointmentComment" Member="Appointment" ThisKey="AppointmentId" OtherKey="AppointmentId" Type="Appointment" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AppointmentNote" Member="AppointmentNotes">
    <Type Name="AppointmentNote">
      <Column Name="AppointmentNoteId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AppointmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Appointment_AppointmentNote" Member="Appointment" ThisKey="AppointmentId" OtherKey="AppointmentId" Type="Appointment" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Client" Member="Clients">
    <Type Name="Client">
      <Column Name="ClientId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DesignerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Client_Appointment" Member="Appointments" ThisKey="ClientId" OtherKey="ClientId" Type="Appointment" />
      <Association Name="Account_Client" Member="Account" ThisKey="AccountId" OtherKey="AccountId" Type="Account" IsForeignKey="true" />
      <Association Name="Designer_Client" Member="Designer" ThisKey="DesignerId" OtherKey="DesignerId" Type="Designer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Designer" Member="Designers">
    <Type Name="Designer">
      <Column Name="DesignerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Designer_WorkSchedule" Member="WorkSchedules" ThisKey="DesignerId" OtherKey="DesignerId" Type="WorkSchedule" />
      <Association Name="Designer_Appointment" Member="Appointments" ThisKey="DesignerId" OtherKey="Designerd" Type="Appointment" />
      <Association Name="Designer_Client" Member="Clients" ThisKey="DesignerId" OtherKey="DesignerId" Type="Client" />
      <Association Name="Account_Designer" Member="Account" ThisKey="AccountId" OtherKey="AccountId" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Photo" Member="Photos">
    <Type Name="Photo">
      <Column Name="PhotoId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateCreatedUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Photo_PhotoAlbumItem" Member="PhotoAlbumItems" ThisKey="PhotoId" OtherKey="PhotoId" Type="PhotoAlbumItem" />
      <Association Name="Account_Photo" Member="Account" ThisKey="AccountId" OtherKey="AccountId" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhotoAlbum" Member="PhotoAlbums">
    <Type Name="PhotoAlbum">
      <Column Name="PhotoAlbumId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DateCreatedUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AccountId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsFeatured" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="isSiteAlbum" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="PhotoAlbum_PhotoAlbumItem" Member="PhotoAlbumItems" ThisKey="PhotoAlbumId" OtherKey="PhotoAlbumId" Type="PhotoAlbumItem" />
    </Type>
  </Table>
  <Table Name="dbo.PhotoAlbumItem" Member="PhotoAlbumItems">
    <Type Name="PhotoAlbumItem">
      <Column Name="PhotoAlbumItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PhotoAlbumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhotoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsCover" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Photo_PhotoAlbumItem" Member="Photo" ThisKey="PhotoId" OtherKey="PhotoId" Type="Photo" IsForeignKey="true" />
      <Association Name="PhotoAlbum_PhotoAlbumItem" Member="PhotoAlbum" ThisKey="PhotoAlbumId" OtherKey="PhotoAlbumId" Type="PhotoAlbum" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserClaims" Member="UserClaims">
    <Type Name="UserClaim">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimType" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimValue" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Account_UserClaim" Member="Account" ThisKey="UserId" OtherKey="UserId" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserLogins" Member="UserLogins">
    <Type Name="UserLogin">
      <Column Name="LoginProvider" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderKey" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Account_UserLogin" Member="Account" ThisKey="UserId" OtherKey="UserId" Type="Account" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserRoles" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Account_UserRole" Member="Account" ThisKey="UserId" OtherKey="UserId" Type="Account" IsForeignKey="true" />
      <Association Name="ApplicationRole_UserRole" Member="ApplicationRole" ThisKey="RoleId" OtherKey="Id" Type="ApplicationRole" IsForeignKey="true" />
    </Type>
  </Table>
</Database>